<a href="https://colab.research.google.com/github/sandeepbansode/Deep-Learning/blob/main/Word_embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [5]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [7]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [31]:
onehot_repr=[one_hot(words,voc_size ,)for words in sent] 
print(onehot_repr)

[[391, 125, 161, 166], [391, 125, 161, 490], [391, 76, 161, 85], [453, 173, 373, 188, 388], [453, 173, 373, 188, 129], [470, 391, 149, 161, 108], [371, 165, 387, 188]]


### Word Embedding Represntation

In [34]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
import numpy as np

In [45]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[391 125 161 166   0   0   0   0]
 [391 125 161 490   0   0   0   0]
 [391  76 161  85   0   0   0   0]
 [453 173 373 188 388   0   0   0]
 [453 173 373 188 129   0   0   0]
 [470 391 149 161 108   0   0   0]
 [371 165 387 188   0   0   0   0]]


In [46]:
## 10 feature dimesnions
dim=10


In [47]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [48]:
 model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [49]:
##'the glass of milk',
embedded_docs[0]

array([391, 125, 161, 166,   0,   0,   0,   0], dtype=int32)

In [50]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 161ms/step


array([[-0.02921522, -0.0114862 , -0.03994988,  0.0464998 , -0.03095111,
         0.01166631, -0.0375784 ,  0.03674622,  0.03868601, -0.00275218],
       [ 0.04810072, -0.02062342, -0.02148866,  0.02949288, -0.04579417,
         0.01984363, -0.03648216,  0.01200781,  0.02858399, -0.01786351],
       [-0.04908064,  0.04034758, -0.01224124, -0.00785011, -0.03247588,
        -0.03811612,  0.04150193, -0.03578038, -0.00791051,  0.0471972 ],
       [ 0.01163181, -0.03968799,  0.0300836 , -0.01248651, -0.04011639,
         0.00604508,  0.02058626,  0.03446141, -0.01757531,  0.00618801],
       [ 0.04014004,  0.03440449,  0.02418074,  0.00245389, -0.01040164,
         0.04912133, -0.04342582,  0.0004244 ,  0.01743868, -0.04845766],
       [ 0.04014004,  0.03440449,  0.02418074,  0.00245389, -0.01040164,
         0.04912133, -0.04342582,  0.0004244 ,  0.01743868, -0.04845766],
       [ 0.04014004,  0.03440449,  0.02418074,  0.00245389, -0.01040164,
         0.04912133, -0.04342582,  0.0004244 

In [51]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 28ms/step
[[[-0.02921522 -0.0114862  -0.03994988  0.0464998  -0.03095111
    0.01166631 -0.0375784   0.03674622  0.03868601 -0.00275218]
  [ 0.04810072 -0.02062342 -0.02148866  0.02949288 -0.04579417
    0.01984363 -0.03648216  0.01200781  0.02858399 -0.01786351]
  [-0.04908064  0.04034758 -0.01224124 -0.00785011 -0.03247588
   -0.03811612  0.04150193 -0.03578038 -0.00791051  0.0471972 ]
  [ 0.01163181 -0.03968799  0.0300836  -0.01248651 -0.04011639
    0.00604508  0.02058626  0.03446141 -0.01757531  0.00618801]
  [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164
    0.04912133 -0.04342582  0.0004244   0.01743868 -0.04845766]
  [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164
    0.04912133 -0.04342582  0.0004244   0.01743868 -0.04845766]
  [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164
    0.04912133 -0.04342582  0.0004244   0.01743868 -0.04845766]
  [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040

In [52]:
embedded_docs[0]

array([391, 125, 161, 166,   0,   0,   0,   0], dtype=int32)

In [53]:
#'the glass of milk'
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 14ms/step
[[-0.02921522 -0.0114862  -0.03994988  0.0464998  -0.03095111  0.01166631
  -0.0375784   0.03674622  0.03868601 -0.00275218]
 [ 0.04810072 -0.02062342 -0.02148866  0.02949288 -0.04579417  0.01984363
  -0.03648216  0.01200781  0.02858399 -0.01786351]
 [-0.04908064  0.04034758 -0.01224124 -0.00785011 -0.03247588 -0.03811612
   0.04150193 -0.03578038 -0.00791051  0.0471972 ]
 [ 0.01163181 -0.03968799  0.0300836  -0.01248651 -0.04011639  0.00604508
   0.02058626  0.03446141 -0.01757531  0.00618801]
 [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164  0.04912133
  -0.04342582  0.0004244   0.01743868 -0.04845766]
 [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164  0.04912133
  -0.04342582  0.0004244   0.01743868 -0.04845766]
 [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164  0.04912133
  -0.04342582  0.0004244   0.01743868 -0.04845766]
 [ 0.04014004  0.03440449  0.02418074  0.00245389 -0.01040164  0.04912133

In [54]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]